### ISSUE TITLE
incompatible with the IntelliJ ver. 233

### ISSUE THREAD

**Issue by anniewillescape** [T45K/IntelliJ-Bitbucket-Server-Coverage-Upload-plugin#18]
Thank you for the wonderful plugin!
My team members frequently use it.

I would be delighted if it could be made compatible with the IntelliJ ver.233.
Thank you.

**Comment by T45K** [comment]
thank you for submitting issue
i updated and uploaded the latest version.
it is now under verification, so you will be able to download it after the verification is completed.
