### ISSUE TITLE
Migrate IntelliJ Platform Gradle Plugin (2.x)

### ISSUE THREAD

**Issue by anniewillescape** [T45K/IntelliJ-Bitbucket-Server-Coverage-Upload-plugin#22]
The Gradle IntelliJ Plugin 1.x does not support building plugins against the IntelliJ Platform 2024.2+ (242+).
Could you please support IntelliJ Platform Gradle Plugin 2.0.0 or higher? 

https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html
https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-migration.html

Or would you let me make this change...?

**Comment by T45K** [comment]
sure, let me check it

**Comment by T45K** [comment]
@anniewillescape 

> Or would you let me make this change...?

ah, it looks fine for me.
may i ask you to do that?

i tried the latest plugin platform before, so it may be helpful for you...
https://github.com/T45K/kotlin_analysis_api_trial/blob/master/build.gradle.kts#L4

**Comment by anniewillescape** [comment]
@T45K 
Thanks for giving me this great opportunity!

Thanks for sharing the reference code as well :)

**Comment by anniewillescape** [comment]
I hit the button to close the issue by mistake. Sorry 🙏
